# Generated by Django 4.0.1 on 2022-01-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_tm', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='名字')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='邮箱')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='电话')),
                ('active', models.BooleanField(verbose_name='是否激活')),
                ('level', models.SmallIntegerField(choices=[(0, 'supervisor'), (1, 'administrator'), (6, 'staff'), (11, 'guest')], default=6, verbose_name='等级')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
            ],
            options={
                'ordering': ['create_tm'],
            },
        ),
        migrations.CreateModel(
            name='CustomSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_tm', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ip', models.GenericIPAddressField(verbose_name='Host')),
                ('port', models.IntegerField(default=22, verbose_name='Port')),
                ('protocol', models.CharField(max_length=16, verbose_name='Protocol')),
                ('username', models.CharField(max_length=16, verbose_name='Username')),
                ('sshkey_login', models.BooleanField(default=False, verbose_name='是否免密登录')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='Password')),
            ],
            options={
                'ordering': ['update_tm'],
                'unique_together': {('ip', 'port', 'protocol', 'username')},
            },
        ),
    ]
