# Generated by Django 4.0.1 on 2022-01-13 02:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_tm', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('system_id', models.IntegerField(default=0, verbose_name='系统ID')),
                ('scan_id', models.UUIDField(default=uuid.UUID('6f0985d4-741c-11ec-a630-080027d71608'), verbose_name='扫描ID')),
                ('ips', models.CharField(max_length=256, verbose_name='扫描的网段')),
                ('ports', models.CharField(max_length=256, verbose_name='扫描的端口')),
                ('more', models.TextField()),
            ],
            options={
                'ordering': ['update_tm'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_tm', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ip', models.GenericIPAddressField(verbose_name='Host')),
                ('port', models.IntegerField(default=22, verbose_name='Port')),
                ('protocol', models.CharField(max_length=16, verbose_name='Protocol')),
                ('username', models.CharField(max_length=16, verbose_name='Username')),
                ('sshkey_login', models.BooleanField(default=False, verbose_name='是否免密登录')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='Password')),
            ],
            options={
                'ordering': ['update_tm'],
                'unique_together': {('ip', 'port', 'protocol', 'username')},
            },
        ),
    ]
